name: PyGSL build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  wrap_and_build:
    # Re-generate SWIG wrappers, then build and test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.10", "3.11" ]

    steps:
      # Checkout the repository contents
      - name: Checkout PyGSL code
        uses: actions/checkout@v4

      # Setup Python version
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: |
           **/pyproject.toml
           **/setup.cfg
           **/requirements*.txt

      # Install dependencies
      - name: Install apt dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libgsl-dev swig
          sudo apt-get install python3-dev python3-pip

      # Install Python dependencies
      - name: Python dependencies
        run: |
          python -m pip install --upgrade pip wheel
          python -m pip install pytest setuptools pycodestyle flake8
          python -m pip install "numpy<2.0"

          # So that one can seee in the output which numpy version was run
          python3 -c 'import numpy; print("numpy version", numpy.__version__)'

      - name: gsl_wrappers
        run: |
          python setup.py gsl_wrappers

      - name: config
        run: |
          python setup.py config

      - name: wheel
        run: |
          python -m pip wheel -w wheel/ ./

      - name: install
        run: |
          # listing a non existing directory fails ..
          ls -l dist/ || echo 'no dist directory'
          ls -l wheel/
          python -m pip install wheel/pygsl-*.whl

      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 pygsl --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 pygsl --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: test
        run: |
          # make sure to move out of the source directory
          cd /tmp
          python -m pytest -s /home/runner/work/pygsl/pygsl/tests

      # Install Python dependencies
      - name: Python dependencies for paladin
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest coverage
          python -m pip install -r requirements.txt
          python -m pip install pycodestyle
          python -m pip install wheel setuptools --upgrade

      - name: install
        run: |
          python -m pip install pygsl

      - name: test
        run: |
          coverage run -m pytest  -v -s tests