
name: Run Unit Test via Pytest  
  
on: [push, pull_request]  
  
jobs:  
  build:  
    runs-on: ubuntu-latest  
    strategy:  
      matrix:  
        python-version: ["3.11"]  
  
    steps:  
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}  
        uses: actions/setup-python@v4  
        with:  
          python-version: ${{ matrix.python-version }}
          node-version: 20

      # Install dependencies
      - name: Install dependencies  
        run: |  
          sudo apt update
          sudo apt install libgsl0-dev libncurses5-dev libreadline6-dev pkg-config swig
          sudo apt install python3-all-dev python3-matplotlib python3-numpy python3-scipy

      # Install Python dependencies
      - name: Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install wheel setuptools --upgrade

      - name: Test with pytest  
        run: |  
          coverage run -m pytest  -v -s tests

      - name: Generate Coverage Report  
        run: |  
          coverage report -m